### ISSUE TITLE
[Feature Request] Add support for part-of-speech STTS tagset to Multi-layer FCS query GUI

### ISSUE THREAD

**Issue by kaizimmer1** [clarin-eric/fcs-sru-aggregator#1]
Hi,
could you add support for the german part-of-speech STTS tagset (1995/1999) to the Multi-Layer FCS query GUI?
>http://www.ims.uni-stuttgart.de/forschung/ressourcen/lexika/TagSets/stts-table.html
Thanks!
Kai

**Comment by ljo** [comment]
@kaizimmer1 This must be a misconception of the FCS 2.0? Since it builds on having a unified query language with a specified PoS-tagset, e.g. the UD v2.0 PoS-tagset. If you actually wanted consulting on the reusable component I am available.
