### ISSUE TITLE
FCS aggregator does not process incoming pre-selection from VLO

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/fcs-sru-aggregator#13]
The connection between the VLO and the FCS aggregator is currently broken. 

For example [this record](https://vlo.clarin.eu/record/hdl_58_11022_47_0000-0007-DF1E-E?fqType=_contentSearchRef:not_empty&fqType=collection:or&fq=collection:Leipzig+Corpora+Collection) (`http://hdl.handle.net/11022/0000-0007-DF1E-E`) has the "Plain text search via Federated Content Search " link and is represented in the FCS aggregator; however clicking the link (i.e. POSTing the hidden form) in the record page doesn't work - that is, the aggregator UI appears without any visible errors but no collections have been preselected either.

The JS console does report: `no context set, selecting all available`.

To give some more details, the following form is generated for the VLO's web interface:

```html
            <form id="id1e2" class="contentSearchForm" method="post" name="id1e2" target="_blank" action="https://spraakbanken.gu.se/ws/fcs/2.0/aggregator/"> 
                <input type="hidden" name="query" id="query" value="" /> 
                <input type="hidden" name="x-aggregation-context" value="{&quot;https://clarinws.informatik.uni-leipzig.de/CQL&quot;: [&quot;hdl:11022/0000-0007-DF1E-E&quot;]}"/> 
                <input type="hidden" name="operation" value="searchRetrieve" /> 
                <input type="hidden" name="version" value="1.2" /> 
            </form> 
```

 And the following parameters are indeed sent in the POST:

* query: `x-aggregation-context | {"http://fedora.clarin-d.uni-saarland.de/sru2/":+["hdl:11858/00-246C-0000-001F-7C6F-1"]}`
* operation: `searchRetrieve`
* version: `1.2`

It might be that the VLO isn't sending the right information but this used to work and I haven't seen documentation specifying a different procedure.

**Comment by twagoo** [comment]
This has been reported before in the CLARIN internal ticket management system at  https://trac.clarin.eu/ticket/945

**Comment by Querela** [comment]
In my local setup, it seems as if the forwarding code throws an error because [`request.getServletContext()`](https://github.com/clarin-eric/fcs-sru-aggregator/blob/01a2eb9414e3e98ae26b3c84febd3bdc27d1edf3/src/main/java/eu/clarin/sru/fcs/aggregator/app/ErrorHandler.java#L92) only returns `null`. Debugging showed that `org.eclipse.jetty.server.handler.ErrorHandler` seems to have a context stored as attribute that can be accessed for this. I'm unsure where/when this change was introduced.

```diff
@@ -92,7 +96,14 @@ public class ErrorHandler extends org.eclipse.jetty.server.handler.ErrorHandler
         if (request.getSession().getAttribute(PARAM_AGGREGATION_CONTEXT) != null) {
             params.append("x-aggregation-context=" + request.getSession().getAttribute(PARAM_AGGREGATION_CONTEXT));
         }
-        RequestDispatcher dispatcher = request.getServletContext().getNamedDispatcher("static");
+        RequestDispatcher dispatcher;
+        ServletContext ctx = request.getServletContext();
+        if (ctx != null) {
+            dispatcher = ctx.getNamedDispatcher("static");
+        } else {
+            ContextHandler.Context ctx2 = (ContextHandler.Context) request.getAttribute(ErrorHandler.ERROR_CONTEXT);
+            dispatcher = ctx2.getNamedDispatcher("static");
+        }
```

**Comment by Querela** [comment]
Should be fixed in https://github.com/clarin-eric/fcs-sru-aggregator/pull/51/commits/1727c0b5cc519e7e88dc1c3a8a8a2ccde39d0efd (#51)
