### ISSUE TITLE
Portulan endpoint not showing up after addition to centre registry

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/fcs-sru-aggregator#17]
https://portulanclarin.net/fcs/ works when side-loaded at https://fcs.clarin-dev.eu/ but does not show up after addition to the [centre registry ](https://centres.clarin.eu/fcs)

Not sure if related but note that a new version of the centre registry has been deployed, see the [changelog](https://github.com/clarin-eric/Centre-Registry/releases/tag/2.3.0) for details

**Comment by ljo** [comment]
The new version of the centre registry is not related from what I can tell now.
One corpus is available now in the corpus selector, e.g CINTIL: 
![portulan-20200729](https://user-images.githubusercontent.com/191478/88795156-db736700-d19f-11ea-82d1-fa27f59fadd3.png)
