### ISSUE TITLE
Update title in navbar to Content Search

### ISSUE THREAD

**Issue by WillemElbers** [clarin-eric/fcs-sru-aggregator#18]
Currently the title displayed in the navbar is `Federated Content Search`. This is a request to change it into `Content Search` to make it inline with https://www.clarin.eu/content/services and https://www.clarin.eu/content/content-search.

**Comment by ljo** [comment]
@WillemElbers OK. Thanks, will do that for next content update. Any hour now.

**Comment by WillemElbers** [comment]
This was discussed with Dieter as well. Just to be complete :)

**Comment by ljo** [comment]
It is committed.

**Comment by WillemElbers** [comment]
Thanks!
