### ISSUE TITLE
ARCHE collections not being listed on the https://contentsearch.clarin.eu/

### ISSUE THREAD

**Issue by zozlak** [clarin-eric/fcs-sru-aggregator#23]
It looks like ARCHE resources are not included in the FCS collections list (nothing from ARCHE/OEAW/ACDH listed in the collections list on the https://contentsearch.clarin.eu/ ).

I guess the reason is a problem with harvesting https://arche.acdh.oeaw.ac.at/fcs/?operation=explain&x-fcs-endpoint-description=true . The endpoint works but (due to high number of small resources) full response generation takes around 160 seconds. Maybe it reaches harvester timeout already...

**Comment by dietervu** [comment]
Looking at the state of the FCS collections in the aggregator today, this issue has been resolved.
