### ISSUE TITLE
[support] LINDAT/CLARIAH-CZ endpoint missing in aggregator

### ISSUE THREAD

**Issue by vidiecan** [clarin-eric/fcs-sru-aggregator#25]
LINDAT/CLARIAH-CZ has 2 endpoints in https://centres.clarin.eu/fcs

Why is 
`http://lindat.mff.cuni.cz/services/fcs-kontext` 
is not present in 
https://contentsearch.clarin.eu/

I tried looking at
https://contentsearch.clarin.eu/rest/statistics
to no avail

**Comment by dietervu** [comment]
Re-checking after the recent migration of the production instance. I now see the endpoint at https://contentsearch.clarin.eu/stats:

![image](https://user-images.githubusercontent.com/8073487/229796406-03308ee2-312e-447f-87f1-a0e7d4ddc09d.png)
