### ISSUE TITLE
Send to Weblicht functionality not working

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/fcs-sru-aggregator#34]
Reported on 26 April 2022 by Iulianna. Steps to reproduce:

- Search for "Elephant" in aggregator
- Select Tagesspiegel hits > View
- Click Use weblicht > Send to weblicht

The [resulting URL](https://contentsearch.clarin.eu/rest/search/381433645/toWeblicht?corpusId=http%3A%2F%2Fdspin.dwds.de%3A8088%2Fddc-sru%2Ftagesspiegel%2F%23http%3A%2F%2Fhdl.handle.net%2F11858%2F00-203C-0000-0029-C1C9-B&filterLanguage=deu) returns:

> error while exporting to weblicht

**Comment by Querela** [comment]
Based on the current code and my local tests, I think the backend services are not available anymore.
It seems first a TCF file is being created and uploaded before forwarding the upload URL to weblicht for processing. [[code](https://github.com/clarin-eric/fcs-sru-aggregator/blob/master/src/main/java/eu/clarin/sru/fcs/aggregator/rest/RestService.java#L303)]
However, the host `ws1-clarind.esc.rzg.mpg.de` [[code](https://github.com/clarin-eric/fcs-sru-aggregator/blob/master/src/main/java/eu/clarin/sru/fcs/aggregator/rest/DataTransfer.java#L30)] does not seem to exist, so it fails.

```java
eu.clarin.sru.fcs.aggregator.rest.DataTransfer: Error uploading http://ws1-clarind.esc.rzg.mpg.de/drop-off/storage/somefilename.tcf javax.ws.rs.ProcessingException java.net.UnknownHostException: ws1-clarind.esc.rzg.mpg.de: Name or service not known
```

**Comment by claus-zinn** [comment]
The server ws1-clarind.esc.rzg.mpg.de was taken down a while ago because of security concerns. It was more or less a public server that anybody (who knew about its existence) could have used to upload and download data. For the future integration with WebLicht (and potentially with the Switchboard), It would be much cleaner for the FCS to store the file locally and make it available via URL to WebLicht. At regular intervals, FCS should then delete the files they provide to WebLicht. (Note: in the Switchboard, data is deleted 3 hours after uploading).

**Comment by Querela** [comment]
Ok, so I didn't just imagine those security issues. And while they could be mitigated by using IP filtering and maybe rate-limiting, that's a lot of effort while some simple caching on the aggregator side can solve this issue much more easily.

In my local test instance, I already have some working implementation that I will later nicely wrap up in a pull request.

---

@claus-zinn, theoretically it already should be possible to use the TCF-export URIs as WebLicht input. But for some reason, it raises some NullPointerException by WebLicht.

> An error has occurred which prevents further processing.
> Unbekannte Ausnahme: java.lang.NullPointerException.
> Please try again later...

To reproduce, perform any basic search and view a single result. Then copy the URL from the _Download > As TCF file_ button. Then do `encodeURIComponent()` on this URL and append it to `https://weblicht.sfs.uni-tuebingen.de/weblicht/?input=`. This should produce a working WebLicht input URL. WebLicht however fails to load anything from it.

So, as long as the search is still cached,
(a) `https://contentsearch.clarin.eu/rest/search/1372673415/download?corpusId=http%3A%2F%2Fdspin.dwds.de%3A8088%2Fddc-sru%2Ftagesspiegel%2F%23http%3A%2F%2Fhdl.handle.net%2F11858%2F00-203C-0000-0029-C1C9-B&format=tcf` (should work in any browser)
&darr;
(b) `https%3A%2F%2Fcontentsearch.clarin.eu%2Frest%2Fsearch%2F1372673415%2Fdownload%3FcorpusId%3Dhttp%253A%252F%252Fdspin.dwds.de%253A8088%252Fddc-sru%252Ftagesspiegel%252F%2523http%253A%252F%252Fhdl.handle.net%252F11858%252F00-203C-0000-0029-C1C9-B%26format%3Dtcf` (already escaped sequences become double escaped with `%` &rarr; `%25`)
&darr;
(c) `https://weblicht.sfs.uni-tuebingen.de/weblicht/?input=https%3A%2F%2Fcontentsearch.clarin.eu%2Frest%2Fsearch%2F1372673415%2Fdownload%3FcorpusId%3Dhttp%253A%252F%252Fdspin.dwds.de%253A8088%252Fddc-sru%252Ftagesspiegel%252F%2523http%253A%252F%252Fhdl.handle.net%252F11858%252F00-203C-0000-0029-C1C9-B%26format%3Dtcf`.

**Comment by claus-zinn** [comment]
Hmm, if I download the TCF manually and upload it into WebLicht via the GUI, then I get the same error. Oxygen also tells me that the TCF has a syntax error (with a weird error message "No CSS file specified". So it seems that WebLicht invocation succeeds, but input parsing fails.

**Comment by Querela** [comment]
Ok. I will take a look into this. That actually helps for bug 🪲 fixing and tracking where inconsistencies come from.
In my local setup, it works but I also did some dependency updates, so I better check this again. The TCC URL download version failed but caching and with its own URL it works. So there might still be something else, so I first try to create the pull request here.

**Comment by claus-zinn** [comment]
Just a note. During the Text+ plenary the new federated content search for lexical resources was demo-ed. Here, WebLicht invocation works, see https://lexfcs-demo.wortschatz-leipzig.de/?&query=Entwicklung (invoke WebLicht, and check URL).
